matrix:
  include:
    - language: php
      php: '7.1'
      os: linux
      before_script:
      - composer install
    - language: node_js
      node_js: '9'
      before_install:
      - yarn global add grunt-cli

